-- changeset nikitasudaev: 1
CREATE TABLE discount_card
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number BIGINT,
    percent INT,
    CONSTRAINT discount_card_pkey PRIMARY KEY (id)
);